export type Product = {
  id: number;
  name: string;
  team: string;
  category: "club" | "national" | "classic";
  price: number;
  image: string;
  badge: string;
  sizes: string[];
};

export const PRODUCTS: Product[] = [
  // CLUB JERSEYS
  {
    id: 1,
    name: "ريال مدريد 2025",
    team: "Real Madrid",
    category: "club",
    price: 260,
    image: "/reamdrid.jpg",
    badge: "الأكثر مبيعاً",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 2,
    name: "برشلونة 2025",
    team: "Barcelona",
    category: "club",
    price: 250,
    image: "/reamdrid.jpg",
    badge: "جديد",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 3,
    name: "ليفربول 2025",
    team: "Liverpool",
    category: "club",
    price: 240,
    image: "/reamdrid.jpg",
    badge: "الأكثر طلباً",
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: 4,
    name: "مانشستر سيتي 2025",
    team: "Manchester City",
    category: "club",
    price: 255,
    image: "/mancity-kit.jpg",
    badge: "",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 5,
    name: "آرسنال 2025",
    team: "Arsenal",
    category: "club",
    price: 235,
    image: "/reamdrid.jpg",
    badge: "",
    sizes: ["S", "M", "L"],
  },
  {
    id: 6,
    name: "تشيلسي 2025",
    team: "Chelsea",
    category: "club",
    price: 245,
    image: "/reamdrid.jpg",
    badge: "",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 7,
    name: "بايرن ميونخ 2025",
    team: "Bayern Munich",
    category: "club",
    price: 260,
    image: "/reamdrid.jpg",
    badge: "",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 8,
    name: "يوفنتوس 2025",
    team: "Juventus",
    category: "club",
    price: 240,
    image: "/reamdrid.jpg",
    badge: "",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 9,
    name: "ميلان 2025",
    team: "AC Milan",
    category: "club",
    price: 235,
    image: "/reamdrid.jpg",
    badge: "",
    sizes: ["S", "M", "L"],
  },
  {
    id: 10,
    name: "انتر ميلان 2025",
    team: "Inter Milan",
    category: "club",
    price: 235,
    image: "/reamdrid.jpg",
    badge: "",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 11,
    name: "باريس سان جيرمان 2025",
    team: "PSG",
    category: "club",
    price: 270,
    image: "/reamdrid.jpg",
    badge: "",
    sizes: ["S", "M", "L"],
  },

  // NATIONAL TEAMS
  {
    id: 12,
    name: "الأرجنتين 2024",
    team: "Argentina",
    category: "national",
    price: 230,
    image: "/argentina-kit.jpg",
    badge: "الأكثر مبيعاً",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 13,
    name: "البرازيل 2024",
    team: "Brazil",
    category: "national",
    price: 235,
    image: "/argentina-kit.jpg",
    badge: "جديد",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 14,
    name: "إسبانيا 2024",
    team: "Spain",
    category: "national",
    price: 225,
    image: "/argentina-kit.jpg",
    badge: "",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 15,
    name: "فرنسا 2024",
    team: "France",
    category: "national",
    price: 240,
    image: "/argentina-kit.jpg",
    badge: "الأكثر طلباً",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 16,
    name: "البرتغال 2024",
    team: "Portugal",
    category: "national",
    price: 230,
    image: "/argentina-kit.jpg",
    badge: "",
    sizes: ["S", "M", "L"],
  },
  {
    id: 17,
    name: "ألمانيا 2024",
    team: "Germany",
    category: "national",
    price: 230,
    image: "/argentina-kit.jpg",
    badge: "",
    sizes: ["S", "M", "L", "XL"],
  },

  // CLASSIC JERSEYS
  {
    id: 18,
    name: "كلاسيك أرسنال 2004",
    team: "Arsenal",
    category: "classic",
    price: 280,
    image: "/italy-kit.jpg",
    badge: "كلاسيكي",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 19,
    name: "كلاسيك مانشستر يونايتد 1999",
    team: "Manchester United",
    category: "classic",
    price: 290,
    image: "/italy-kit.jpg",
    badge: "أسطوري",
    sizes: ["L", "XL", "XXL"],
  },
  {
    id: 20,
    name: "كلاسيك ميلان 2007",
    team: "Milan",
    category: "classic",
    price: 275,
    image: "/italy-kit.jpg",
    badge: "",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 21,
    name: "كلاسيك ليفربول 1980",
    team: "Liverpool",
    category: "classic",
    price: 295,
    image: "/italy-kit.jpg",
    badge: "نادر",
    sizes: ["M", "L"],
  },
  {
    id: 22,
    name: "كلاسيك برشلونة 1992",
    team: "Barcelona",
    category: "classic",
    price: 285,
    image: "/italy-kit.jpg",
    badge: "",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 23,
    name: "كلاسيك ريال مدريد 2002",
    team: "Real Madrid",
    category: "classic",
    price: 300,
    image: "/italy-kit.jpg",
    badge: "أسطوري",
    sizes: ["L", "XL", "XXL"],
  },
];